GET http://127.0.0.1:5000/admin/b9f999f6-8937-48b7-9b8e-0b16dd53c073 HTTP/1.1
# Cookie: session=da8591ff-a3ec-4d74-a7fd-157d64173608; HttpOnly; Path=/

### Login

POST http://127.0.0.1:5000/admin/login HTTP/1.1
content-type: application/json

{
 "email": "user3@example.com",
 "password": "password3"
}

### register

POST http://127.0.0.1:5000/admin/register HTTP/1.1
content-type: application/json

{
 "email": "user8@example.com",
"password": "password6",
"username": "test user"
}


