
### get all churches
GET http://127.0.0.1:5000/church HTTP/1.1


### get church by ID

GET http://127.0.0.1:5000/church/65ddfb544c05a82c93084bf3 HTTP/1.1


### register

POST http://127.0.0.1:5000/church/register HTTP/1.1
content-type: application/json
Cookie: session=b0cef75d-5664-428e-a826-e546d83599d2; HttpOnly; Path=/

{
    "name": "New Dimension",
    "denomination": "Non-denominational",
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "country": "USA",
        "postal_code": "12345"
    },
    "contact": {
        "phone": "555-1234",
        "email": "info@newdimension.com",
        "website": "http://www.newdimension.com"
    },
    "services": [
        {"day": "Sunday", "time": "10:00 AM"},
        {"day": "Wednesday", "time": "7:00 PM"}
    ],
    "about": "Welcome to New Dimension...",
    "image_url": "http://www.newdimension.com/logo.png"
}



