
### get all churches
GET http://127.0.0.1:5000/church HTTP/1.1


### get church by ID

GET http://127.0.0.1:5000/church/65db45ff9359153e97ef2f17 HTTP/1.1


### register

POST http://127.0.0.1:5000/church/register HTTP/1.1
content-type: application/json
Cookie: session=pBrkZmY4eZ8rpaBLFypjig41iih10xFJPEFuYdeSCuo; HttpOnly; Path=/

{
    "name": "Community Church",
    "denomination": "Non-denominational",
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "country": "USA",
        "postal_code": "12345"
    },
    "contact": {
        "phone": "555-1234",
        "email": "info@communitychurch.com",
        "website": "http://www.communitychurch.com"
    },
    "services": [
        {"day": "Sunday", "time": "10:00 AM"},
        {"day": "Wednesday", "time": "7:00 PM"}
    ],
    "about": "Welcome to Community Church...",
    "image_url": "http://www.communitychurch.com/logo.png",
    "admins": [],
    "members": []
}



### Add members to a church

POST http://127.0.0.1:5000/church/members/65ddfb544c05a82c93084bf3 HTTP/1.1
content-type: application/json
Cookie: session=pBrkZmY4eZ8rpaBLFypjig41iih10xFJPEFuYdeSCuo; HttpOnly; Path=/

{"members":["1234546", "23456", "123234453", "65db2b198bf35f699cec1312"]}
