@SERVER_URL = http://127.0.0.1:5000
@COOKIE = t5-vGUa1x_P-brM77AnaQcPAbxzmExHN2DG1Tg7GOUc;



### get all churches
GET http://127.0.0.1:5000/church HTTP/1.1


### get church by ID

GET http://127.0.0.1:5000/church/65ddfb544c05a82c93084bf3 HTTP/1.1


### register

POST http://127.0.0.1:5000/church/register HTTP/1.1
content-type: application/json
Cookie: session={{COOKIE}} HttpOnly; Path=/

{
    "name": "New dimension church",
    "denomination": "Non-denominational",
    "address": {
        "street": "409 Galand Street",
        "city": "Ermelo",
        "state": "mpumalanga",
        "country": "Southa africa",
        "postal_code": "2351"
    },
    "contact": {
        "phone": "555-1234",
        "email": "info@africanimmanuel.com",
        "website": "http://www.africanimmanuel.com"
    },
    "services": [
        {"day": "Sunday", "time": "10:00 AM"},
        {"day": "Wednesday", "time": "7:00 PM"}
    ],
    "about": "Welcome to African Immanuel Church...",
    "image_url": "http://www.africanimmanuel.com/logo.png"
}



