
@SERVER_URL = http://127.0.0.1:5000
@COOKIE = 62b38473-5875-4f17-8440-5c493f5c7574;


### Add members to a church - church Id

POST {{SERVER_URL}}/members/65df0781fc87ea59fa235e06 HTTP/1.1
content-type: application/json
Cookie: session={{COOKIE}} HttpOnly; Path=/

{"member": "65def18ad82cccb20f68e155"}

### Get Church members - church Id

GET {{SERVER_URL}}/members/65df0a024627456fdff40ff5 HTTP/1.1



