### Add members to a church - church Id

POST http://127.0.0.1:5000/members/65de57c14455dbd5794017d8 HTTP/1.1
content-type: application/json
Cookie: session=0bb37868-fc20-49d5-bcab-9a5b3d6569cf; HttpOnly; Path=/

{"member": "65def18ad82cccb20f68e155"}

### Get Church members - church Id

GET http://127.0.0.1:5000/members/65de57c14455dbd5794017d8 HTTP/1.1



